services:
  sphinx: &build_cache
    build:
      cache_from:
        - type=local,src=/tmp/.buildx-cache
      cache_to:
        - type=local,dest=/tmp/.buildx-cache-new

  # gosu:
  #   <<: *build_cache

  # tini:
  #   <<: *build_cache

  # pipenv:
  #   <<: *build_cache

  # vsi:
  #   <<: *build_cache
