name: Build Docs

on:
  push:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      # This won't work currently, as docker-compose ignores the "in use" builder instance
      # and docker-compose/docker buildx bake won't accept cache_to!!!!
      # - name: Set up Docker Buildx
      #   id: buildx
      #   uses: docker/setup-buildx-action@master

      # - name: Cache Docker layers
      #   uses: actions/cache@v2
      #   with:
      #     path: /tmp/.buildx-cache
      #     key: ${{ runner.os }}-buildx-cache-${{ github.sha }}
      #     restore-keys: |
      #       ${{ runner.os }}-buildx-cache

      - name: Build sphinx image and compile docs
        run: |
          cd docs
          source setup.env
          just ci-compile-docs

      # - name: Move cache
      #   run: |
      #     rm -rf /tmp/.buildx-cache
      #     mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy-docs:
    runs-on: ubuntu-latest
    needs: build-docs
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy docs
        run: |
          cd docs
          source setup.env
          just ci-deploy-docs "${GITHUB_ACTOR}" "${{ secrets.GITHUB_TOKEN }}"