name: Build Docs

on:
  push:

jobs:
  build-docs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build sphinx image
        run: |
          cd docs
          source setup.env
          just ci-compile-docs
      - name: Deploy docs
        run: |
          cd docs
          source setup.env
          just ci-deploy-docs "${GITHUB_ACTOR}" "${{ secrets.GITHUB_TOKEN }}"